##### core #####

# use proper terminal colors
set -g default-terminal "tmux-256color"
set -as terminal-overrides ",*:Tc"

# reduce key delay
set -sg escape-time 0


##### pane navigation (vim motions only) #####

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# nicer splits
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

##### reload #####

bind r source-file ~/.tmux.conf \; display "tmux reloaded"

##### theme #####

# source oxocarbon powerline theme
source-file ~/.tmux/themes/oxocarbon-powerline.tmux



# tmux resurrect
run-shell ~/.tmux/plugins/tmux-resurrect/resurrect.tmux

# tforge begin: shpherd
unbind-key `
bind-key ` run-shell "/usr/bin/env bash /home/ni3rav/.tforge/sessions/shpherd.sh"
# tforge end: shpherd
